"""Initial Commit

Revision ID: 3a9ab4385a00
Revises:
Create Date: 2025-09-22 18:32:43.219423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a9ab4385a00"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flights",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "status", sa.Boolean(), nullable=True, comment="Status of current flight."
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="flight_data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flights", schema="flight_data")
    # ### end Alembic commands ###
