"""Initial Commit

Revision ID: 43f0715b0b36
Revises: 
Create Date: 2025-09-22 17:34:58.361721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f0715b0b36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('Id', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True, comment='Status of current flight.'),
    sa.PrimaryKeyConstraint('Id'),
    schema='flight_data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights', schema='flight_data')
    # ### end Alembic commands ###
