"""Added monitoring schema

Revision ID: ceca22b3011f
Revises: ecfbc1fa8639
Create Date: 2025-09-27 13:40:38.764356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ceca22b3011f"
down_revision: Union[str, Sequence[str], None] = "ecfbc1fa8639"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airline",
        sa.Column("icao", sa.String(), nullable=False),
        sa.Column("iata", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("short", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("icao"),
        schema="flight_data",
    )
    op.create_table(
        "airport",
        sa.Column("icao_code", sa.String(), nullable=False),
        sa.Column("iata_code", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("altitude", sa.Float(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("country_code", sa.String(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("offset", sa.Integer(), nullable=True),
        sa.Column("offset_hours", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("icao_code"),
        schema="flight_data",
    )
    op.create_table(
        "testTable",
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="monitoring",
    )
    op.create_table(
        "aircraft",
        sa.Column("registration", sa.String(), nullable=False),
        sa.Column("airline_id", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["airline_id"],
            ["flight_data.airline.icao"],
        ),
        sa.PrimaryKeyConstraint("registration"),
        schema="flight_data",
    )
    op.create_table(
        "flights",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "status", sa.Boolean(), nullable=True, comment="Status of current flight."
        ),
        sa.Column("origin_airport_icao_code", sa.String(), nullable=True),
        sa.Column("destination_airport_icao_code", sa.String(), nullable=True),
        sa.Column("aircraft_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["flight_data.aircraft.registration"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_airport_icao_code"],
            ["flight_data.airport.icao_code"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_airport_icao_code"],
            ["flight_data.airport.icao_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="flight_data",
    )
    op.create_table(
        "images",
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("src", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("copyright", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("aircraft_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["flight_data.aircraft.registration"],
        ),
        sa.PrimaryKeyConstraint("url"),
        schema="flight_data",
    )
    op.create_table(
        "flight_current_status",
        sa.Column("flight_id", sa.String(), nullable=False),
        sa.Column("live", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("event_ts_utc", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight_data.flights.id"],
        ),
        sa.PrimaryKeyConstraint("flight_id"),
        schema="flight_data",
    )
    op.create_table(
        "trail",
        sa.Column("flight_id", sa.String(), nullable=False),
        sa.Column("event_ts_utc", sa.BigInteger(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("alt", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight_data.flights.id"],
        ),
        sa.PrimaryKeyConstraint("flight_id", "event_ts_utc"),
        schema="flight_data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trail", schema="flight_data")
    op.drop_table("flight_current_status", schema="flight_data")
    op.drop_table("images", schema="flight_data")
    op.drop_table("flights", schema="flight_data")
    op.drop_table("aircraft", schema="flight_data")
    op.drop_table("testTable", schema="monitoring")
    op.drop_table("airport", schema="flight_data")
    op.drop_table("airline", schema="flight_data")
    # ### end Alembic commands ###
